version: "3.9"
services:
  cic-ussd:
    image: ghcr.io/grassrootseconomics/cic-ussd/cic-ussd:latest
    restart: unless-stopped
    env_file:
      - ussd.env
    ports:
      - '9000:9000'
    networks:
      - cic      
networks:
  cic:
    external: true
