version: "3.9"
services:
  watchtower:
    image: containrrr/watchtower:latest
    command: --cleanup --label-enable -i 120
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  cic-chain-events:
    image: ghcr.io/grassrootseconomics/cic-chain-events/cic-chain-events:latest
    restart: unless-stopped    
    env_file:
      - events.env
    ports:
      - '5001:5000'
    labels:
      - com.centurylinklabs.watchtower.enable=true
  cic-custodial:
    image: ghcr.io/grassrootseconomics/cic-custodial/cic-custodial:latest
    restart: unless-stopped
    depends_on:
      - cic-chain-events
    env_file:
      - custodial.env
    ports:
      - '5002:5000'
    labels:
      - com.centurylinklabs.watchtower.enable=true
  cic-graph:
    image: hasura/graphql-engine:v2.20.0
    restart: unless-stopped
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: secret
    env_file:
      - graph.env
    ports:
      - '8081:8080'
  cic-ussd:
    image: cic-ussd:latest
    restart: unless-stopped
    env_file:
      - ussd.env
    ports:
      - '9001:9000'
    labels:
      - com.centurylinklabs.watchtower.enable=true
networks:
  default:
    external: true
    name: cic