receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: cic-custodial
          metrics_path: '/metrics'
          scrape_interval: 5s
          static_configs:
            - targets: ['cic-custodial:5000']
        - job_name: cic-chain-events
          metrics_path: '/metrics'
          scrape_interval: 5s
          static_configs:
            - targets: ['cic-chain-events:5000']            

exporters:
  # Fill in this part

extensions:
  health_check:
  pprof:
  zpages:

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      # Fill in this part
      exporters: []
