version: "3.9"
services:
  benthos:
    image: jeffail/benthos:4.12
    restart: unless-stopped
    volumes:
      - ./benthos.yaml:/benthos.yaml
    networks:
      - cic
  cic-chain-events:
    image: ghcr.io/grassrootseconomics/cic-chain-events/cic-chain-events:v0.5.0-alpha
    restart: unless-stopped
    depends_on:
      - benthos       
    env_file:
      - events.env
    ports:
      - '8085:8085'
    networks:
      - cic      
  cic-custodial:
    image: ghcr.io/grassrootseconomics/cic-custodial/cic-custodial:v0.2.5-alpha
    command: ./cic-custodial -queries queries.sql
    restart: unless-stopped
    depends_on:
      - cic-chain-events      
    env_file:
      - custodial.env
    ports:
      - '5005:5005'
    networks:
      - cic         
networks:
  cic:
    external: true       