version: "3.9"
services:
  redis:
    image: redis:6-alpine
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - cic-deploy-redis:/data
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cic      
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cic_custodial
    volumes:
      - cic-deploy-pg:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cic      
  nats:
    image: nats:2.9
    restart: unless-stopped
    command: "-js -sd /nats/data"
    volumes:
      - cic-deploy-nats:/nats/data
    ports:
      - "127.0.0.1:4222:4222"
      - "127.0.0.1:8222:8222"
    networks:
      - cic      
  asynqmon:
    image: hibiken/asynqmon
    restart: unless-stopped
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - cic      
volumes:
  cic-deploy-pg:
    driver: local
  cic-deploy-redis:
    driver: local
  cic-deploy-nats:
    driver: local

networks:
  cic:
    external: true       