version: "3.9"
services:
  cic-indexer:
    image: jeffail/benthos:4
    restart: unless-stopped
    volumes:
      - ./indexer.yaml:/benthos.yaml
    networks:
      - cic
  cic-notify:
    image: ghcr.io/grassrootseconomics/cic-notify/cic-notify:latest
    restart: unless-stopped
    env_file:
      - notify.env
    ports:
      - '5003:5000'
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - cic      
networks:
  cic:
    external: true       