input:
  label: cic_chain_events
  nats_jetstream:
    urls:
      - nats://nats:4222
    subject: CHAIN.transfer
    durable: benthos_sub
    stream: CHAIN
    deliver: all
pipeline:
  processors:
    - label: epoch_convert
      bloblang: |
        root = this
        root.timestamp = (this.timestamp).ts_format()
        root.txType = if this.txType == "transfer" {
          "TRANSFER"
        } else if this.txType == "mintTo" {
          "MINT_TO"
        } else {
          "TRANSFER_FROM"  
        }
output:
  broker:
    outputs:
      - label: cic_graph_indexer
        sql_insert:
          driver: postgres
          dsn: postgres://postgres:postgres@postgres:5432/cic_graph?sslmode=disable
          table: transactions
          columns: [
            tx_hash,
            block_number,
            tx_index,
            voucher_address,
            sender_address,
            recipient_address,
            tx_value,
            tx_type,
            date_block,
            success
          ]
          args_mapping: |-
            root = [
              this.transactionHash,
              this.block,
              this.transactionIndex,
              this.contractAddress,
              this.from,
              this.to,
              this.value,
              this.txType,
              this.timestamp,
              this.success,
            ]
      - label: logg
        stdout:
          codec: lines

